version: "3.8"

services:
  db:
    image: postgres:15
    container_name: mymarket_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mymarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: mymarket_api
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mymarket
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: standartpass
    command: server /data --console-address ":9001"
    restart: always

volumes:
  postgres_data:
  minio_data: